id: P009616
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:41:01.162667
source_metadata:
  id: bdr:W1KG12669
  title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་ཡོན་ཏན་རིན་པོ་ཆེ་སྡུད་པ།
  author: ''
  volumes:
    fc992745a1fa4c6383c24e2313df1d59:
      image_group_id: I1KG12697
      title: ''
      volume_number: 1
      total_pages: 216
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
